### ISSUE TITLE
Scroller est fonctionnellement cassé sur votre site

### ISSUE THREAD

**Issue by Arthur-Milchior** [ebanDev/eban.dev#1]
Reproduction:
* Aller sur https://eban.eu.org/
* scroller un bon coup, comme sur la majorité des sites webs quand on veut descendre d'une page entière

Résultat attendu:
* scroller petit à petit et avoir la 2ème page apparaître

Résultat obtenu:
* La page 2 apparait quasi immédiatement, le scrolling continue encore, et on arrive à la page 3. Rendant la page 2 compliqué à obtenir si on est habitué au scroll.

Bug obtenu sur Chrome à jour sur ubuntu

**Comment by ebanDev** [comment]
Bonjour,
Merci pour ton issue et désolé pour ma réponse tardive, un fix va être apporté sous peu ;)
(Chrome qui gère mal le scroll snapping 😅)

**Comment by ebanDev** [comment]
Et voilàààà ! 😃

**Comment by Arthur-Milchior** [comment]
De rien. 
Y a aucune urgence. Pour être honnête, je doute de retourner régulièrement sur ton site, donc ça m'affecte assez peu. C'est surtout pour toi/les gens qui veulent voir son contenu.
J'ai juste tendance à regarder les profils des gens qui intéragissent avec le poste annonçant GSoC sur AnkiDroid, au cas où ça me permette de découvrir des gens avant qu'ils candidatent

**Comment by ebanDev** [comment]
D'acc ! En tout cas merci beaucoup d'avoir prit le temps de me faire ce signalement ! ;)
